apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: flowagent
  labels:
    app: registry
    component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
