apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resources in mrliouai namespace
namespace: mrliouai

resources:
- ../../base
- ../../../apps/mongodb
- ../../../apps/module-a
- ../../../apps/orchestrator
- ../../../apps/nextjs-frontend

labels:
- pairs:
    environment: production
    version: v1

images:
- name: asia-east1-docker.pkg.dev/mrliouai/mrliouai/module-a
  newTag: latest
- name: asia-east1-docker.pkg.dev/mrliouai/mrliouai/orchestrator
  newTag: latest
- name: asia-east1-docker.pkg.dev/mrliouai/mrliouai/nextjs-frontend
  newTag: latest
