'use strict';
// backend/core/scaffolds/scaffold-templates/index.js
// MRL Scaffold Templates — 最小 stub 模板集
// origin_signature: MrLiouWord

// ── README ─────────────────────────────────────────────────────────
function readme(ctx) {
  return `# ${ctx.title}
> Generated by MRL_ProductPack_Generator_v1
> origin_signature: MrLiouWord
> scaffold_id: ${ctx.scaffoldId}
> pack_id: ${ctx.packId}
> mode: ${ctx.modeLabel}
> generated_at: ${ctx.generatedAt}

---

## 核心方向

**${ctx.coreJudgment}**

${ctx.summary}

---

## 第一版範圍

${(ctx.scope || []).map((s, i) => `${i + 1}. ${s}`).join('\n')}

---

## 執行順序

${(ctx.steps || []).map((s, i) => `Step ${i + 1}：${s}`).join('\n')}

---

## 先做 vs 先不做

${(ctx.doVsNot || []).map(s => `- ${s}`).join('\n')}

---

## 快速啟動

\`\`\`bash
cp .env.example .env
# 填入 ANTHROPIC_API_KEY、STRIPE_* 等必填項目
npm install
npm run dev
\`\`\`

或 Docker：

\`\`\`bash
cd deploy
docker compose up -d --build
\`\`\`

---

## 需要人工補完的地方

- [ ] \`.env\` 填入真實金鑰
- [ ] 前端頁面的實際文案與樣式
- [ ] AI prompt 依你的產品調整
- [ ] Stripe Price ID（到 Stripe Dashboard 建立後填入）
- [ ] 確認 BASE_URL 對應你的網域

---

*此 scaffold 由 ProductPack 自動生成，為骨架起點。*
`;
}

// ── Scaffold Notes ─────────────────────────────────────────────────
function scaffoldNotes(ctx) {
  const pageList = (ctx.pages || []).map(p =>
    `| ${p.name.padEnd(12)} | ${p.purpose.padEnd(20)} | ${p.priority} |`
  ).join('\n');

  const flowList = (ctx.flows || []).map(f =>
    `${String(f.step).padStart(2, '0')}. **${f.name}** — ${f.description}`
  ).join('\n');

  return `# Scaffold Notes — ${ctx.title}
> pack_id: ${ctx.packId} · mode: ${ctx.modeLabel}

## 頁面清單

| 頁面         | 用途                 | 優先級  |
|-------------|---------------------|---------|
${pageList}

## 使用者流程

${flowList}

## 定價模式

- 單次：NT$${ctx.pricing.once_amount}
- 月費：NT$${ctx.pricing.sub_amount}/月
- 幣別：${ctx.pricing.currency}

## 部署目標

- Target：${ctx.deployment.target || 'DL580'}
- Stack：${(ctx.deployment.stack || []).join(' + ')}
- 啟動指令：\`${ctx.deployment.command || 'docker compose up -d --build'}\`

---

*此文件由 Scaffold Generator 自動生成。*
`;
}

// ── HTML Page Stub ─────────────────────────────────────────────────
function htmlPage({ title, slug, page, coreJudgment, packId, scaffoldId, generatedAt }) {
  const pageTitle = {
    index:   '首頁',
    app:     '分析入口',
    pricing: '方案與定價',
    product: '主打入口',
    success: '付款成功',
    cancel:  '付款取消',
  }[page.name] || page.name;

  return `<!DOCTYPE html>
<html lang="zh-TW">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} — ${pageTitle}</title>
  <!--
    Scaffold: ${scaffoldId}
    Pack:     ${packId}
    Page:     ${page.name} (${page.purpose})
    Priority: ${page.priority}
    Generated: ${generatedAt}
    origin_signature: MrLiouWord

    TODO: 替換此 scaffold 為實際頁面內容
    核心方向：${coreJudgment}
  -->
  <link rel="stylesheet" href="/assets/style.css">
</head>
<body>

<!-- NAV -->
<nav class="nav">
  <div class="nav__inner">
    <a href="/" class="nav__logo">${title}.</a>
    <div class="nav__links">
      <a href="/pricing.html" class="nav__link">方案</a>
      <a href="/app.html" class="nav__cta">開始</a>
    </div>
  </div>
</nav>

<!-- MAIN: ${pageTitle} -->
<main style="padding:60px 20px;max-width:760px;margin:0 auto;">
  <h1 style="font-size:2rem;margin-bottom:16px;">${pageTitle}</h1>
  <p style="color:#888;margin-bottom:32px;">
    <!-- TODO: 填入 ${page.name} 頁面的實際內容 -->
    ${page.purpose}
  </p>

  ${page.name === 'index' ? `
  <!-- Hero Placeholder -->
  <div style="padding:40px;background:#111;border:1px dashed #333;border-radius:8px;text-align:center;margin-bottom:24px;">
    <div style="color:#888;font-size:12px;margin-bottom:12px;">HERO SECTION PLACEHOLDER</div>
    <h2 style="color:#fff;margin-bottom:8px;">[主標題]</h2>
    <p style="color:#aaa;">[副標題]</p>
    <a href="/app.html" style="display:inline-block;margin-top:20px;padding:12px 28px;background:#e8b84b;color:#000;border-radius:6px;text-decoration:none;font-weight:600;">
      開始
    </a>
  </div>` : ''}

  ${page.name === 'app' ? `
  <!-- App Input Placeholder -->
  <div style="padding:24px;background:#111;border:1px dashed #333;border-radius:8px;">
    <div style="color:#888;font-size:12px;margin-bottom:12px;">INPUT SECTION PLACEHOLDER</div>
    <textarea style="width:100%;min-height:120px;background:#1a1a1a;border:1px solid #333;border-radius:6px;padding:14px;color:#fff;font-size:14px;resize:none;" placeholder="把你的問題丟進來..."></textarea>
    <div style="margin-top:12px;text-align:right;">
      <button style="padding:10px 24px;background:#e8b84b;color:#000;border:none;border-radius:6px;font-weight:600;cursor:pointer;">開始分析</button>
    </div>
  </div>` : ''}

  ${page.name === 'pricing' ? `
  <!-- Pricing Placeholder -->
  <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;">
    <div style="padding:24px;background:#111;border:1px dashed #333;border-radius:8px;">
      <div style="color:#888;font-size:12px;">單次方案</div>
      <div style="font-size:2rem;color:#fff;font-weight:700;margin:8px 0;">NT$299</div>
      <p style="color:#aaa;font-size:14px;">一次完整分析</p>
    </div>
    <div style="padding:24px;background:#111;border:2px solid #e8b84b;border-radius:8px;">
      <div style="color:#e8b84b;font-size:12px;">月費方案 · 推薦</div>
      <div style="font-size:2rem;color:#fff;font-weight:700;margin:8px 0;">NT$499</div>
      <p style="color:#aaa;font-size:14px;">無限次分析 / 月</p>
    </div>
  </div>` : ''}

</main>

<script src="/assets/app.js"></script>
</body>
</html>
`;
}

// ── CSS Stub ───────────────────────────────────────────────────────
function cssStub({ title, scaffoldId }) {
  return `/* ${title} — Scaffold CSS Stub
   scaffold_id: ${scaffoldId}
   origin_signature: MrLiouWord
   TODO: 替換為實際樣式
*/

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, sans-serif; background: #0c0c0d; color: #f0f0f2; line-height: 1.6; }
a { color: inherit; text-decoration: none; }
button { cursor: pointer; font-family: inherit; }

.nav { border-bottom: 1px solid #242428; padding: 0 20px; height: 56px; display: flex; align-items: center; }
.nav__inner { max-width: 760px; margin: 0 auto; width: 100%; display: flex; align-items: center; justify-content: space-between; }
.nav__logo { font-weight: 700; font-size: 18px; color: #f0f0f2; }
.nav__links { display: flex; gap: 16px; align-items: center; }
.nav__link { font-size: 14px; color: #a1a1aa; }
.nav__cta { padding: 7px 16px; background: #e8b84b; color: #000; border-radius: 6px; font-size: 13px; font-weight: 600; }
`;
}

// ── App JS Stub ────────────────────────────────────────────────────
function appJsStub({ title, scaffoldId, packId }) {
  return `// ${title} — Scaffold App.js Stub
// scaffold_id: ${scaffoldId}
// pack_id: ${packId}
// origin_signature: MrLiouWord
// TODO: 替換為實際互動邏輯

'use strict';

// ── State ──────────────────────────────────────────────────────────
const state = { token: null, sessionId: null, analysisId: null };

// ── Init ───────────────────────────────────────────────────────────
async function init() {
  state.token = localStorage.getItem('app_token') || '';
  if (!state.token) await initSession();
}

async function initSession() {
  try {
    const res = await fetch('/api/session', { method: 'POST', headers: { 'Content-Type': 'application/json' } });
    const data = await res.json();
    if (data.token) { state.token = data.token; localStorage.setItem('app_token', data.token); }
  } catch {}
}

// ── API Helper ─────────────────────────────────────────────────────
async function apiFetch(url, opts = {}) {
  const headers = { 'Content-Type': 'application/json' };
  if (state.token) headers['Authorization'] = 'Bearer ' + state.token;
  const res = await fetch(url, { ...opts, headers, body: opts.body ? JSON.stringify(opts.body) : undefined });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || '請求失敗');
  return data;
}

init().catch(console.error);
`;
}

// ── Server.js Stub ─────────────────────────────────────────────────
function serverJs({ title, slug, scaffoldId }) {
  return `'use strict';
// ${title} — backend/server.js
// scaffold_id: ${scaffoldId}
// origin_signature: MrLiouWord
// TODO: 補充完整路由與中間件

const express = require('express');
const path    = require('path');
const app     = express();
const PORT    = process.env.PORT || 3000;

app.use(express.json({ limit: '512kb' }));
app.use('/assets', express.static(path.join(__dirname, '../frontend/assets')));

// TODO: 補充 routes
app.use('/', require('./routes/api'));

app.get('/health', (_req, res) => res.json({ status: 'ok', service: '${slug}', origin: 'MrLiouWord' }));

app.listen(PORT, () => console.log(\`[${slug}] running on :\${PORT}\`));
`;
}

// ── Config.js Stub ─────────────────────────────────────────────────
function configJs({ scaffoldId }) {
  return `'use strict';
// config.js — scaffold_id: ${scaffoldId}
// origin_signature: MrLiouWord
require('dotenv').config();

module.exports = {
  port:                parseInt(process.env.PORT || '3000'),
  nodeEnv:             process.env.NODE_ENV || 'development',
  baseUrl:             process.env.BASE_URL || 'http://localhost:3000',
  dbPath:              process.env.DB_PATH || './storage/db.sqlite',
  jwtSecret:           process.env.JWT_SECRET || 'dev-secret',
  anthropicApiKey:     process.env.ANTHROPIC_API_KEY || '',
  stripeSecretKey:     process.env.STRIPE_SECRET_KEY || '',
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET || '',
  stripePriceOnce:     process.env.STRIPE_PRICE_ONCE || '',
  stripePriceSub:      process.env.STRIPE_PRICE_SUB || '',
  adminKey:            process.env.ADMIN_KEY || 'dev-admin',
  originSignature:     'MrLiouWord',
};
`;
}

// ── Route Stubs ────────────────────────────────────────────────────
function routeApiJs({ slug, scaffoldId }) {
  return `'use strict';
// routes/api.js — scaffold_id: ${scaffoldId}
// origin_signature: MrLiouWord
// TODO: 補充完整 analyze / result API

const express = require('express');
const router  = express.Router();

router.post('/api/session', (_req, res) => {
  res.json({ token: 'scaffold-token', sessionId: 'scaffold-session' });
});

router.post('/api/analyze', async (_req, res) => {
  // TODO: 接上 Core_Generator
  res.json({ analysis_id: 'scaffold-id', result: {}, is_partial: true });
});

router.get('/api/result/:id', (_req, res) => {
  res.status(404).json({ error: 'Not implemented yet' });
});

module.exports = router;
`;
}

function routePaymentJs({ scaffoldId }) {
  return `'use strict';
// routes/payment.js — scaffold_id: ${scaffoldId}
// origin_signature: MrLiouWord
// TODO: 補充 Stripe checkout 邏輯

const express = require('express');
const router  = express.Router();

router.post('/api/pay/once',         (_req, res) => res.json({ error: 'Not implemented yet' }));
router.post('/api/pay/subscription', (_req, res) => res.json({ error: 'Not implemented yet' }));

module.exports = router;
`;
}

function routeWebhookJs({ scaffoldId }) {
  return `'use strict';
// routes/webhook.js — scaffold_id: ${scaffoldId}
// origin_signature: MrLiouWord
// TODO: 補充 Stripe webhook 處理（confirmation → ledger → unlock）

const express = require('express');
const router  = express.Router();

router.post('/webhook/stripe', express.raw({ type: 'application/json' }), (_req, res) => {
  res.json({ received: true });
});

module.exports = router;
`;
}

// ── Module Stubs ───────────────────────────────────────────────────
function moduleAiJs({ scaffoldId }) {
  return `'use strict';
// modules/ai.js — scaffold_id: ${scaffoldId}
// origin_signature: MrLiouWord
// TODO: 補充 Anthropic SDK 呼叫與 category-aware prompt

async function analyze(problemText, category) {
  throw new Error('ai.js not implemented yet — connect Core_Generator');
}

module.exports = { analyze };
`;
}

function moduleOrderJs({ scaffoldId }) {
  return `'use strict';
// modules/order.js — scaffold_id: ${scaffoldId}
// origin_signature: MrLiouWord
// TODO: 補充 order CRUD

function createOrder(_opts) { throw new Error('order.js not implemented yet'); }
function getOrder(_id)      { return null; }

module.exports = { createOrder, getOrder };
`;
}

function moduleLedgerJs({ scaffoldId }) {
  return `'use strict';
// modules/ledger.js — scaffold_id: ${scaffoldId}
// origin_signature: MrLiouWord
// TODO: 補充 ledger 寫入（唯一真相層）
// 規則：只寫入，不修改，不刪除

function writeEvent(_opts) { /* TODO */ }
function hasUnlockEvent(_orderId) { return false; }

module.exports = { writeEvent, hasUnlockEvent };
`;
}

function moduleConfirmationJs({ scaffoldId }) {
  return `'use strict';
// modules/confirmation.js — scaffold_id: ${scaffoldId}
// origin_signature: MrLiouWord
// TODO: 付款確認核心（沒有 confirmation 不可解鎖）

async function confirm(_opts) {
  throw new Error('confirmation.js not implemented yet');
}

module.exports = { confirm };
`;
}

// ── Schema SQL ─────────────────────────────────────────────────────
function schemaSql({ slug, scaffoldId }) {
  return `-- ${slug} schema.sql
-- scaffold_id: ${scaffoldId}
-- origin_signature: MrLiouWord
-- TODO: 補充完整 schema（參考 MRL_Product_v1 storage/schema.sql）

PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS analyses (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  problem_text TEXT NOT NULL,
  partial_result TEXT,
  full_result TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  analysis_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  amount INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ledger (
  id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  order_id TEXT,
  analysis_id TEXT,
  amount INTEGER,
  meta_json TEXT,
  origin_sig TEXT NOT NULL DEFAULT 'MrLiouWord',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
`;
}

// ── Package.json ───────────────────────────────────────────────────
function packageJson({ slug, title, scaffoldId }) {
  return JSON.stringify({
    name:        slug,
    version:     '0.1.0',
    description: `${title} — Generated by MRL_ProductPack_Generator_v1`,
    main:        'backend/server.js',
    scripts: {
      start: 'node backend/server.js',
      dev:   'NODE_ENV=development node backend/server.js',
    },
    dependencies: {
      '@anthropic-ai/sdk': '^0.39.0',
      'better-sqlite3':    '^9.4.0',
      dotenv:              '^16.0.0',
      express:             '^4.18.0',
      jsonwebtoken:        '^9.0.0',
      stripe:              '^14.0.0',
    },
    _scaffold_id: scaffoldId,
    _origin:      'MrLiouWord',
  }, null, 2);
}

// ── Deploy Files ───────────────────────────────────────────────────
function dockerfile({ slug, scaffoldId }) {
  return `# Dockerfile — scaffold_id: ${scaffoldId}
# origin_signature: MrLiouWord
# target: DL580 G9
# TODO: 依實際需求調整

FROM node:20-slim

RUN apt-get update && apt-get install -y python3 make g++ curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev

COPY backend/ ./backend/
COPY frontend/ ./frontend/
COPY storage/schema.sql ./storage/schema.sql

RUN mkdir -p /app/storage /app/logs

HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \\
  CMD curl -f http://localhost:3000/health || exit 1

EXPOSE 3000
CMD ["node", "backend/server.js"]
`;
}

function dockerCompose({ slug, scaffoldId }) {
  return `# docker-compose.yml — scaffold_id: ${scaffoldId}
# origin_signature: MrLiouWord
# TODO: 確認 volume 路徑對應 DL580 實際目錄

services:
  app:
    build: .
    container_name: ${slug}-app
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_PATH=/app/storage/db.sqlite
    volumes:
      - /opt/${slug}/storage:/app/storage
      - /opt/${slug}/logs/app:/app/logs
    networks: [app-net]
    expose: ["3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  nginx:
    image: nginx:1.25-alpine
    container_name: ${slug}-nginx
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/${slug}/logs/nginx:/var/log/nginx
    depends_on:
      app:
        condition: service_healthy
    networks: [app-net]

networks:
  app-net:
    driver: bridge
`;
}

function nginxConf({ slug, scaffoldId }) {
  return `# nginx.conf — scaffold_id: ${scaffoldId}
# origin_signature: MrLiouWord

upstream ${slug.replace(/-/g, '_')}_backend {
  server app:3000;
  keepalive 32;
}

server {
  listen 80;
  server_name _;

  proxy_http_version 1.1;
  proxy_set_header Host              $host;
  proxy_set_header X-Real-IP         $remote_addr;
  proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  location /webhook/ { proxy_pass http://${slug.replace(/-/g, '_')}_backend; proxy_read_timeout 30s; }
  location /api/     { proxy_pass http://${slug.replace(/-/g, '_')}_backend; }
  location /assets/  { proxy_pass http://${slug.replace(/-/g, '_')}_backend; expires 1h; }
  location /health   { proxy_pass http://${slug.replace(/-/g, '_')}_backend; access_log off; }
  location /         { proxy_pass http://${slug.replace(/-/g, '_')}_backend; proxy_read_timeout 120s; }

  client_max_body_size 1m;
  gzip on;
  gzip_types text/plain text/css application/json application/javascript;
}
`;
}

function envExample({ slug, scaffoldId }) {
  return `# .env.example — scaffold_id: ${scaffoldId}
# origin_signature: MrLiouWord
# 複製為 .env 並填入真實值

PORT=3000
NODE_ENV=production
BASE_URL=https://your-domain.com

JWT_SECRET=REPLACE_WITH_STRONG_SECRET

DB_PATH=/app/storage/db.sqlite

ANTHROPIC_API_KEY=sk-ant-REPLACE
ANTHROPIC_MODEL=claude-opus-4-5

STRIPE_SECRET_KEY=sk_live_REPLACE
STRIPE_WEBHOOK_SECRET=whsec_REPLACE
STRIPE_PRICE_ONCE=price_REPLACE
STRIPE_PRICE_SUB=price_REPLACE

ADMIN_KEY=REPLACE_WITH_ADMIN_KEY
LOG_LEVEL=info
`;
}

function gitignore({ scaffoldId }) {
  return `# .gitignore — scaffold_id: ${scaffoldId}
.env
node_modules/
storage/db.sqlite
storage/*.sqlite
logs/
`;
}

module.exports = {
  readme, scaffoldNotes, htmlPage,
  cssStub, appJsStub, serverJs, configJs,
  routeApiJs, routePaymentJs, routeWebhookJs,
  moduleAiJs, moduleOrderJs, moduleLedgerJs, moduleConfirmationJs,
  schemaSql, packageJson,
  dockerfile, dockerCompose, nginxConf, envExample, gitignore,
};
