// Generated by Wrangler by running `wrangler types`

interface Env {
	PARTICLE_VAULT: KVNamespace;
	AUTH_VAULT: KVNamespace;
	VERSION: "4.0.0";
	ORIGIN: "MrLiouWord";
	GATE_ENGINE: DurableObjectNamespace /* GateEngine from particle-edge-v4 */;
	PARTICLES: R2Bucket;
	DB: D1Database;
}
